"use client";

import { useState, useEffect } from "react";
import { supabase } from "@/lib/supabaseClient";
import { 
  HiDownload, 
  HiDocumentReport, 
  HiRefresh,
  HiCheckCircle,
  HiExclamation
} from "react-icons/hi";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function ReportsPage() {
  const [assessments, setAssessments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generatingId, setGeneratingId] = useState<string | null>(null);

  // 1. Fetch Completed/Active Assessments
  const fetchAssessments = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("assessments")
      .select("*")
      .order("created_at", { ascending: false });
      
    if (error) console.error(error);
    else setAssessments(data || []);
    setLoading(false);
  };

  useEffect(() => { fetchAssessments(); }, []);

  // 2. Generate PDF Logic
  const generateReport = async (assessment: any) => {
    setGeneratingId(assessment.id);

    try {
      // A. Fetch Deep Data (Controls + Evidence)
      const { data: controls } = await supabase
        .from("controls")
        .select(`*, evidence(*)`)
        .eq("assessment_id", assessment.id);

      if (!controls) throw new Error("No controls found");

      // B. Calculate Stats
      const total = controls.length;
      // Count 'Failed' specifically based on your new taxonomy
      const failed = controls.filter(c => c.status === 'Failed').length;
      const passed = controls.filter(c => c.status === 'Compliant').length;
      const score = total === 0 ? 0 : Math.round((passed / total) * 100);

      // C. Initialize PDF
      const doc = new jsPDF();

      // --- PAGE 1: COVER ---
      doc.setFillColor(15, 23, 42); // Dark Blue Header
      doc.rect(0, 0, 210, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.text("System Security Plan (SSP)", 14, 25);
      
      doc.setFontSize(10);
      doc.setTextColor(200, 200, 200);
      doc.text(`Generated by Vibe Compliance Studio`, 14, 32);

      // Info Block
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(14);
      doc.text(`Assessment: ${assessment.title}`, 14, 60);
      
      doc.setFontSize(11);
      doc.setTextColor(100, 100, 100);
      doc.text(`Standard: ${assessment.standard}`, 14, 68);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 74);

      // Score Bar (Simple Rectangles)
      doc.setDrawColor(0);
      doc.setFillColor(240, 240, 240);
      doc.roundedRect(14, 90, 180, 10, 3, 3, 'F'); // Background
      
      doc.setFillColor(56, 189, 248); // Sky Blue Progress
      const fillWidth = (180 * score) / 100;
      doc.roundedRect(14, 90, fillWidth, 10, 3, 3, 'F');

      doc.setTextColor(0, 0, 0);
      doc.text(`Compliance Score: ${score}%`, 14, 85);

      // --- PAGE 2: GAP ANALYSIS TABLE ---
      doc.text("Gap Analysis (Failed & Missing Controls)", 14, 120);
      
      // Filter for anything not Compliant
      const failedControls = controls.filter(c => c.status !== 'Compliant');
      
      const tableRows = failedControls.map(c => [
        c.control_code,
        c.status,
        c.description ? c.description.substring(0, 80) + (c.description.length > 80 ? '...' : '') : 'No description'
      ]);

      autoTable(doc, {
        startY: 125,
        head: [['ID', 'Status', 'Description']],
        body: tableRows,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [15, 23, 42] },
        // --- FIX IS HERE: Cast raw data to string array ---
        didParseCell: function(data) {
            const rawRow = data.row.raw as string[]; // Type assertion
            if (data.section === 'body' && rawRow[1] === 'Failed') {
                data.cell.styles.textColor = [220, 38, 38]; // Red color
            }
        }
      });

      // --- SAVE ---
      doc.save(`SSP_Report_${assessment.title.replace(/\s+/g, '_')}.pdf`);

    } catch (err: any) {
      console.error(err);
      alert("Failed to generate report: " + err.message);
    } finally {
      setGeneratingId(null);
    }
  };

  return (
    <div className="p-8 text-gray-300 h-full overflow-y-auto">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-2xl font-bold text-white mb-2">Compliance Reports</h1>
          <p className="text-sm text-gray-400">Generate Audit-Ready PDFs (SSP, POA&M).</p>
        </div>
        <button onClick={fetchAssessments} className="p-2 bg-gray-800 hover:bg-gray-700 rounded-lg">
            <HiRefresh />
        </button>
      </div>

      <div className="bg-[#1e293b]/50 border border-gray-800 rounded-xl overflow-hidden">
        {loading ? (
            <div className="p-12 text-center text-gray-500">Loading assessments...</div>
        ) : assessments.length === 0 ? (
            <div className="p-12 text-center text-gray-500">No assessments available.</div>
        ) : (
            <table className="w-full text-left text-sm">
                <thead className="bg-gray-900/50 text-gray-400 uppercase font-medium">
                    <tr>
                        <th className="px-6 py-4">Assessment Title</th>
                        <th className="px-6 py-4">Standard</th>
                        <th className="px-6 py-4">Score</th>
                        <th className="px-6 py-4 text-right">Action</th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-gray-800">
                    {assessments.map((asm) => (
                        <tr key={asm.id} className="hover:bg-gray-800/30 transition">
                            <td className="px-6 py-4 font-medium text-white">{asm.title}</td>
                            <td className="px-6 py-4">
                                <span className="px-2 py-1 rounded bg-blue-900/20 text-blue-400 border border-blue-900 text-xs">
                                    {asm.standard}
                                </span>
                            </td>
                            <td className="px-6 py-4 font-mono text-[#38bdf8]">{asm.progress || 0}%</td>
                            <td className="px-6 py-4 text-right">
                                <button 
                                    onClick={() => generateReport(asm)}
                                    disabled={generatingId === asm.id}
                                    className="inline-flex items-center gap-2 px-3 py-1.5 bg-gray-800 hover:bg-gray-700 text-white rounded border border-gray-700 transition disabled:opacity-50"
                                >
                                    {generatingId === asm.id ? "Generating..." : (
                                        <>
                                            <HiDownload className="text-gray-400" /> Download PDF
                                        </>
                                    )}
                                </button>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        )}
      </div>
    </div>
  );
}